# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the Yfine desktop app (pywebview)."""

a = Analysis(
    ["desktop.py"],
    pathex=["."],
    datas=[
        ("templates", "templates"),
        ("static", "static"),
        ("locales", "locales"),
        ("alembic", "alembic"),
        ("alembic.ini", "."),
        ("plugins/installed", "plugins/installed"),
        ("plugins/__init__.py", "plugins"),
        ("plugins/registry.py", "plugins"),
        ("plugins/scanner.py", "plugins"),
        ("plugins/manager.py", "plugins"),
        ("plugins/state.py", "plugins"),
    ],
    hiddenimports=[
        # uvicorn internals
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.http.h11_impl",
        "uvicorn.protocols.http.httptools_impl",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "uvicorn.lifespan.off",
        # pywebview + Qt backend (required on Linux/Windows/macOS)
        "webview",
        "webview.platforms.qt",
        "qtpy",
        "PyQt5",
        "PyQt5.QtCore",
        "PyQt5.QtGui",
        "PyQt5.QtWidgets",
        "PyQt5.QtWebEngine",
        "PyQt5.QtWebEngineWidgets",
        "PyQt5.QtWebEngineCore",
        "PyQt5.QtWebChannel",
        "PyQt5.QtNetwork",
        "PyQt5.QtPrintSupport",
        # models
        "models",
        "models.movement",
        "models.notification",
        "models.recurring",
        "models.saving",
        "models.setting",
        "models.source",
        "models.tag",
        "models.whim",
        # schemas
        "schemas",
        "schemas.movement",
        "schemas.notification",
        "schemas.recurring",
        "schemas.saving",
        "schemas.setting",
        "schemas.source",
        "schemas.tag",
        "schemas.whim",
        # routers
        "routers",
        "routers.data",
        "routers.movements",
        "routers.notifications",
        "routers.pages",
        "routers.plugins",
        "routers.recurring",
        "routers.savings",
        "routers.settings",
        "routers.sources",
        "routers.tags",
        "routers.whims",
        # services
        "services",
        "services.dashboard",
        "services.data",
        "services.movements",
        "services.notifications",
        "services.recurring",
        "services.savings",
        "services.settings",
        "services.sources",
        "services.tags",
        "services.whims",
        "services.pdf_export",
        # plugins
        "plugins",
        "plugins.manager",
        "plugins.registry",
        "plugins.scanner",
        "plugins.state",
        # security
        "security",
        "cryptography",
        "cryptography.fernet",
        "cryptography.hazmat.primitives.kdf.pbkdf2",
        "cryptography.hazmat.primitives.hashes",
        "cryptography.hazmat.primitives.serialization",
        "cryptography.hazmat.primitives.asymmetric.rsa",
        "cryptography.x509",
        "itsdangerous",
        # other
        "database",
        "i18n",
        "scheduler",
        "multipart",
        "sqlmodel",
        "apscheduler",
        "apscheduler.schedulers.background",
        "apscheduler.triggers.interval",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="yfine",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="yfine",
)

import os as _os
import sys as _sys

if _sys.platform == "darwin":
    _icon = "static/icon.icns" if _os.path.exists("static/icon.icns") else "static/icon.png"
    app = BUNDLE(
        coll,
        name="Yfine.app",
        icon=_icon,
        bundle_identifier="com.alexdevflow.yfine",
        info_plist={
            "CFBundleName": "Yfine",
            "CFBundleDisplayName": "Yfine",
            "CFBundleShortVersionString": "1.0.0",
            "CFBundleVersion": "1",
            "NSHighResolutionCapable": True,
            "LSMinimumSystemVersion": "11.0",
            "LSApplicationCategoryType": "public.app-category.finance",
        },
    )
