"""add_date_format_to_settings

Revision ID: 0f323efeee70
Revises: c08b023a6a38
Create Date: 2026-03-30 13:27:43.804332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f323efeee70'
down_revision: Union[str, Sequence[str], None] = 'c08b023a6a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('date_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='dd/mm/yyyy'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'date_format')
    # ### end Alembic commands ###
