"""add hide_net_worth and last_source_id to settings

Revision ID: 3928ebb81706
Revises: 63bafc066d5e
Create Date: 2026-04-07 15:03:49.859322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3928ebb81706'
down_revision: Union[str, Sequence[str], None] = '63bafc066d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('hide_net_worth', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('settings', sa.Column('last_source_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'last_source_id')
    op.drop_column('settings', 'hide_net_worth')
    # ### end Alembic commands ###
