"""add lan_access to settings

Revision ID: 77fb7438de78
Revises: b7f8a2c1d3e4
Create Date: 2026-04-14 19:11:49.393190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77fb7438de78'
down_revision: Union[str, Sequence[str], None] = 'b7f8a2c1d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    result = conn.execute(sa.text("PRAGMA table_info(settings)"))
    columns = [row[1] for row in result]
    if 'lan_access' not in columns:
        op.add_column('settings', sa.Column('lan_access', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # Update existing rows that might have NULL
    conn.execute(sa.text("UPDATE settings SET lan_access = 0 WHERE lan_access IS NULL"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'lan_access')
    # ### end Alembic commands ###
