"""add_exclude_from_stats_to_sources

Revision ID: c08b023a6a38
Revises: e53452959bd3
Create Date: 2026-03-30 12:53:33.905445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c08b023a6a38'
down_revision: Union[str, Sequence[str], None] = 'e53452959bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('exclude_from_stats', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'exclude_from_stats')
    # ### end Alembic commands ###
